### ISSUE TITLE
Gulp task - Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by BrainyGuy** [canjs/can-compile#27]
The Grunt task has a dependency on 'glob', but does not install it.

**Comment by bhaveshvavdiya** [comment]
I am using node version 0.10.35 & npm version 1.4.28 then after I am getting same error

**Comment by daffl** [comment]
Are you using version 0.7.1?

**Comment by bhaveshvavdiya** [comment]
I changed my node version to 0.6.21 and it solved my error.
Thanks for help.

**Comment by daffl** [comment]
Node 0.6? That sounds a little outdated compared to the current 0.12?

**Comment by bhaveshvavdiya** [comment]
What I am using is five year old project and it needs node version less than 0.7
