### ISSUE TITLE
Not working with stache and canjs 2.1.x

### ISSUE THREAD

**Issue by daniel-franz** [canjs/can-compile#40]
With the current version and canjs 2.1.x the output is:
```
   can.stache("<div></div>")
```
instead of 
```
   can.view.preloadStringRenderer('templates_example_stache', can.stache("<div></div>"));
```

Which seems to be caused by 9080e532fa863754bc3d9935fbe8be164876b7b1

**Comment by Maddis1337** [comment]
actually it only triggers when the file extension is .stache instead of .mustache
