### ISSUE TITLE
Drop dependency on JSDom - installation issues on all platforms

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/can-compile#43]
JSDom relies on contextify, which has been known to have issues with `node-gyp` on all platforms: Windows, OSX, and Linux. `can.view` relies on a very small subset of the DOM api - something like [can-simple-dom](https://github.com/canjs/can-simple-dom) should be used instead.

**Comment by daffl** [comment]
I don't think it does anymore in its latest version but it is only compatible with Node >= 4 and io.js but can-simple-dom would be a much leaner and faster solution (and might also give us the ability to use can-compile as a RequireJS plugin which only allows synchronous view compilation).

**Comment by DesignByOnyx** [comment]
This was fixed by #45
