### ISSUE TITLE
Can compile it's failing on redirects

### ISSUE THREAD

**Issue by paul321** [canjs/can-compile#47]
Im trying to use can compile to build a project but it's failing for few days now, because of this url 

http://canjs.com/release/2.3.5/can.jquery.js

Which returns

```
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>

```

The right url it starts with https

**Comment by daffl** [comment]
Thank you. I really thought it'd follow the redirect. I set canjs.com up to also serve the release via http so everything should work as expected again.
