### ISSUE TITLE
Grunt 1.0 does not satisfy can-compile's peerDependencies requirements

### ISSUE THREAD

**Issue by mikegioia** [canjs/can-compile#49]
Hi there -

I think can-compile's peerDependency on ~0.4.0 is causing a problem for grunt 1.0 installs, either local or global. Is it possible to add ^0.4.0 to allow for 1.0 versions of grunt? I don't think I can use this without forking as of now :(

Thanks for any help you may have. Here's the full error report:

```
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer can-compile@0.10.0 wants grunt@~0.4.0

npm ERR! System Linux 3.19.0-56-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "can-compile"
npm ERR! cwd /home/***/client
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/***/npm-debug.log
npm ERR! not ok code 0
```

**Comment by daffl** [comment]
Are you using NPM 3? It should just ignore the peer dependency. Either way, if you can create a PR with the peer dependency removed (https://github.com/canjs/can-compile/blob/master/package.json#L50-L52) I can make a new patch release that should fix it for you.

**Comment by mikegioia** [comment]
I'm using 1.4.21, which I'm assuming is in Ubuntu 15.04's apt repo. I don't think I can get NPM3 unless I change sources, but I'm no longer using can-compile so this ticket could just be closed. Sorry for the trouble.
