### ISSUE TITLE
Remove dependencies on core CanJS and DOM libraries to increase Node compatibility

### ISSUE THREAD

**Issue by rjgotten** [canjs/can-compile#5]
While such dependencies are fine if you can work with a global Node.js installation and a working npm install of jsdom (and crucially; contextify), it completely bombs when trying to integrate with existing build-chains.

This is a problem in particular for MSBuild-driven builds such as is the case with Visual Studio or TFS build server.

How hard would it be to use *only* the EJS compiler itself to produce the template and nothing else? (Or alternatively; how hard would it be to shim a minimal underlying DOM library on which to build up CanJS?)

**Comment by daffl** [comment]
This is closed by moving to can-simple-dom via #45
