### ISSUE TITLE
Very old node

### ISSUE THREAD

**Issue by paul321** [canjs/can-compile#50]
Can js is depending on very old node version and grunt task keeps showing this warning
npm WARN engine can-compile@0.10.1: wanted: {"node":"~0.10"} (current: {"node":"4.4.3","npm":"2.11.3"})

Could this line be removed from package.json?

**Comment by daffl** [comment]
Yes. It seems to work fine with latest. If you submit a PR that removes it from the `package.json` I will publish a new version right away.
