### ISSUE TITLE
Fix: Domains for new Subdomain Style

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-compile#52]
Kevin Phillips @phillipskevin 18:21
@ablackthorn you say this is breaking your app in production?

ablackthorn @ablackthorn 18:23
We use can-compile to store compiled templates in a database, so yes it broke in production. I modified resolveScripts.js to use the new urls to fix it.

**Comment by frank-dspeed** [comment]
https://github.com/frank-dspeed/can-compile/blob/master/lib/resolveScripts.js

Little Idea about this.

**Comment by Yerrak** [comment]
I would propose to just follow redirects for resolving the script urls.
There might (again) come the day where redirects occur and I would assume that the redirects themselves will be kept updated while the url itself might change again.

We just used `var http = require('follow-redirects').http;` (see https://github.com/olalonde/follow-redirects/) to make sure the redirect urls resolve correctly.

**Comment by frank-dspeed** [comment]
@Yerrak thx for the nice module tip will watch into the code it looks realy usefull :)

**Comment by Schweinepriester** [comment]
+1000

**Comment by andre-cgn** [comment]
+9000

**Comment by chasenlehara** [comment]
We’ve restored the `/release/` scripts on canjs.com so this should no longer be an issue.
