### ISSUE TITLE
TypeError: Cannot read property 'view' of undefined

### ISSUE THREAD

**Issue by paul321** [canjs/can-compile#54]
Hey

Out of nowhere i keep getting this error without modifying anything, it was working fine 3 days ago, the property win.can does not exists, is this something related to can 3.x release?

/Users/Paul/Work/js/desktop/node_modules/can-compile/lib/compile.js:57
    var canViewTagsCallbacks = can.view.Scanner.tags || can.view.callbacks && can.view.callbacks._tags;
                                  ^

TypeError: Cannot read property 'view' of undefined
    at /Users/Paul/Work/js/desktop/node_modules/can-compile/lib/compile.js:57:35
    at /Users/Paul/Work/js/.desktop/node_modules/can-compile/lib/compile.js:19:9
    at /Users/Paul/Work/js/desktop/node_modules/can-simple-window/lib/can-simple-window.js:27:4
    at IncomingMessage.onEnd (/Users/Paul/Work/js/desktop/node_modules/can-simple-window/lib/doc-helpers.js:31:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by paul321** [comment]
yes this url returns 404
http://v2.canjs.com/release/2.3.9/
or this one
http://v2.canjs.com/release/

**Comment by pYr0x** [comment]
https://v2.canjs.com/docs/index.html

**Comment by pYr0x** [comment]
Can-compile is not compatible with can 3.0

**Comment by paul321** [comment]
Nope im using 2.3.x and can-compile tries to download some of the files from the folders that doesn't exists anymore

Here si the code

`var defaultPaths = {
  'jquery': Handlebars.compile('http://ajax.googleapis.com/ajax/libs/jquery/{{version}}/jquery.min.js'),
  'can': Handlebars.compile('http://canjs.com/release/{{version}}/can.jquery.js'),
  'ejs': Handlebars.compile('http://canjs.com/release/{{version}}/can.ejs.js'),
  'mustache': Handlebars.compile('http://canjs.com/release/{{version}}/can.view.mustache.js'),
  'stache': Handlebars.compile('http://canjs.com/release/{{version}}/can.stache.js')
};
`

**Comment by paul321** [comment]
i just uploaded these files on our server and modify the script and it's working again, so this must be the problem

**Comment by daffl** [comment]
I added the `release` folder back. There's probably many things other than can-compile that link to those so it shouldn't just go away, even with a new version. Should work again, now.

**Comment by ypanyukov** [comment]
The problem is not solved - https://www.dropbox.com/s/94vkpm8s54y94rk/Screenshot%202016-12-09%2014.10.47.png?dl=0 even latest returns 404 - https://www.dropbox.com/s/fbj8x6km98ron1f/Screenshot%202016-12-09%2014.11.33.png?dl=0.

Please, fix!

**Comment by matthewp** [comment]
@ypanyukov We're looking into it.

**Comment by daffl** [comment]
The filenames are wrong. For some reason it's `can.view.mustache.system.js` and `can.view.stache.system.js`. I don't know why (or if those are the right files) but it looks like this has been happening for a while.

**Comment by matthewp** [comment]
Yeah, I noticed this as well. Are those the right files? It doesn't look like we ever had a `can.view.mustache.js`, but that is referenced in this project.

**Comment by paul321** [comment]
404 on http://v2.canjs.com/release/ and cancompile doesn't work anymore

**Comment by bmomberger-bitovi** [comment]
@paul321 try can-compile v0.11 and let me know if it doesn't work for you
