### ISSUE TITLE
http://canjs.com/release/2.3.27/can.view.mustache.js 404

### ISSUE THREAD

**Issue by ypanyukov** [canjs/can-compile#55]
For some reason can-compile cannot compile sources. As I understood the problem is in https://github.com/canjs/can-compile/blob/e1a066d5f4fcc83a044e64240adc7b7f0084ff7f/lib/resolveScripts.js#L10

**Comment by pYr0x** [comment]
duplicated https://github.com/canjs/can-compile/issues/54

**Comment by chasenlehara** [comment]
Closing this in favor of https://github.com/canjs/can-compile/issues/56
